### ISSUE TITLE
[11.0] l10n_es_aeat_sii - module l10n.es.aeat.sii.password UNFOUND

### ISSUE THREAD

**Issue by FlyingPigSolutions** [acysos/odoo-addons#33]
Trying to install the module on ubuntu server 16.04 I get this error:
Could  #it be a library missing?

> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/odoo/models.py", line 982, in _validate_fields
>     check(self)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
>     self.postprocess_and_fields(view.model, view_doc, view.id)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 957, in postprocess_and_fields
>     self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
>     raise ValueError(message)
> ValueError: Modèle non trouvé : l10n.es.aeat.sii.password
> 
> Contexte de l'erreur :
> Vue `l10n.es.aeat.sii.password.wizard`
> [view_id: 1700, xml_id: n/a, model: l10n.es.aeat.sii.password, parent_id: n/a]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
>     id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
>     record = record.create(values)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
>     return super(View, self).create(self._compute_defaults(values))
>   File "/home/odoo/odoo-server/odoo/models.py", line 3302, in create
>     self._fields[key].determine_inverse(record)
>   File "/home/odoo/odoo-server/odoo/fields.py", line 1070, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
>     view.write(data)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/home/odoo/odoo-server/odoo/models.py", line 3024, in write
>     self._write(old_vals)
>   File "/home/odoo/odoo-server/odoo/models.py", line 3177, in _write
>     self._validate_fields(vals)
>   File "/home/odoo/odoo-server/odoo/models.py", line 986, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> odoo.exceptions.ValidationError: ("Erreur lors de la validation de la contrainte\n\nModèle non trouvé : l10n.es.aeat.sii.password\n\nContexte de l'erreur :\nVue `l10n.es.aeat.sii.password.wizard`\n[view_id: 1700, xml_id: n/a, model: l10n.es.aeat.sii.password, parent_id: n/a]", None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/odoo/odoo-server/odoo/http.py", line 647, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/home/odoo/odoo-server/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/home/odoo/odoo-server/odoo/http.py", line 689, in dispatch
>     result = self._call_function(**self.params)
>   File "/home/odoo/odoo-server/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/home/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/home/odoo/odoo-server/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/home/odoo/odoo-server/odoo/http.py", line 933, in __call__
>     return self.method(*args, **kw)
>   File "/home/odoo/odoo-server/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/home/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/home/odoo/odoo-server/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/home/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-43>", line 2, in button_immediate_install
>   File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/home/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/home/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/home/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
>     loaded_modules, update_module)
>   File "/home/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/home/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
>     _load_data(cr, module_name, idref, mode, kind='data')
>   File "/home/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
>     tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
>     obj.parse(doc.getroot(), mode=mode)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 738, in parse
>     self.parse(rec, mode)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
>     exc_info[2]
>   File "/home/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/home/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
>     id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
>     record = record.create(values)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
>     return super(View, self).create(self._compute_defaults(values))
>   File "/home/odoo/odoo-server/odoo/models.py", line 3302, in create
>     self._fields[key].determine_inverse(record)
>   File "/home/odoo/odoo-server/odoo/fields.py", line 1070, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
>     view.write(data)
>   File "/home/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/home/odoo/odoo-server/odoo/models.py", line 3024, in write
>     self._write(old_vals)
>   File "/home/odoo/odoo-server/odoo/models.py", line 3177, in _write
>     self._validate_fields(vals)
>   File "/home/odoo/odoo-server/odoo/models.py", line 986, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> odoo.tools.convert.ParseError: "Erreur lors de la validation de la contrainte
> 
> Modèle non trouvé : l10n.es.aeat.sii.password
> 
> Contexte de l'erreur :
> Vue `l10n.es.aeat.sii.password.wizard`
> [view_id: 1700, xml_id: n/a, model: l10n.es.aeat.sii.password, parent_id: n/a]
> None" while parsing /home/odoo/odoo-server/addons/l10n_es_aeat_sii/wizard/aeat_sii_password_view.xml:5, near
> <record id="l10n_es_sii_password_wizard_view" model="ir.ui.view">
>             <field name="name">l10n.es.aeat.sii.password.wizard</field>
>             <field name="model">l10n.es.aeat.sii.password</field>
>             <field name="arch" type="xml">
>                 <form string="Insert Password">
>                     <group>
>                         <field name="password" password="True"/>
>                         <field name="folder"/>
>                     </group>
>                     <footer>
>                         <button name="get_keys" type="object" string="Obtain Keys" class="oe_highlight"/>
>                         or
>                         <button string="Cancel" class="oe_link" special="cancel"/>
>                     </footer>
>                  </form>
>             </field>
>         </record>

**Comment by FlyingPigSolutions** [comment]
Reinstalling the module from scratch I always get this error:
`module 'lib' has no attribute 'SSL_ST_INIT'`

It can be corrected by upgrading pyOpenSSL (depending on version try following):
`sudo python -m easy_install --upgrade pyOpenSSL` [didn't work on my case]
> Don't forget to **reboot** server, in terminal `sudo reboot`, because just refreshing the page is not enough
**or**

`sudo easy_install3 --upgrade pyOpenSSL` 👍 
**or**
> Don't forget to **reboot** server, in terminal `sudo reboot`, because just refreshing the page is not enough

```
pip uninstall pyOpenSSL
pip install pyOpenSSL
```
> Don't forget to **reboot** server, in terminal `sudo reboot`, because just refreshing the page is not enough

**or**
`pip install pyOpenSSL==16.2.0`
> Don't forget to **reboot** server, in terminal `sudo reboot`, because just refreshing the page is not enough
