### ISSUE TITLE
[8.0] l10n_es_aeat_sii - customer invoice write error

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [acysos/odoo-addons#8]
Hi,
I've encountered an error while trying to create a customer invoice with a "normal" user, with the "Financial Manager" group set. Is it only me?

Kind regards,

Luis J. Salvatierra

------------------------
Hola,
He encontrado un error al intentar crear una factura de cliente con un usuario "normal", con el grupo "Gestor financiero" establecido. ¿Sólo me ocurre a mi?

Un cordial saludo,

Luis J. Salvatierra

```bash
2018-01-23 15:33:09,676 16163 ERROR odoo openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  ...

  File "/home/ljsalvatierra/workspace/odoo/acysos/l10n_es_aeat_sii/models/account_invoice.py", line 150, in create
    invoice = super(AccountInvoice, self).create(vals)

  ...

  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/models.py", line 4135, in create
    self._fields[key].determine_inverse(record)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/fields.py", line 953, in determine_inverse
    self.inverse(records)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/fields.py", line 574, in _inverse_related
    other[self.related[-1]] = record_value[record]
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/models.py", line 5688, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/fields.py", line 871, in __set__
    record.write({self.name: self.convert_to_write(value)})
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/addons/base/res/res_company.py", line 310, in write
    return super(res_company, self).write(cr, uid, ids, values, context=context)

  ...

  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/models.py", line 3531, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/ljsalvatierra/workspace/odoo/submodules/ocb/openerp/addons/base/ir/ir_model.py", line 772, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Lo siento, no est\xe1 autorizado para modificar este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Administration/Access Rights\n\n(Modelo de documento: res.company)')
```

A quick solution for me was poping the "sii_enabled" element from the "vals" dictionary as follows.

------------------------

Una rápida solución para mi ha sido sacar el elemento "sii_enabled" del diccionario "vals" de la siguiente manera.

```python
    @api.model
    def create(self, vals):
        if not vals.get('fiscal_position', False):
            partner = self.env['res.partner'].browse(vals['partner_id'])
            raise exceptions.Warning(_(
                "No Fiscal Position configured for the partner %s") % (
                    partner.name))
        if not vals.get('registration_key', False) and \
                vals.get('fiscal_position', False):
            fp = self.env['account.fiscal.position'].browse(
                vals['fiscal_position'])
            if vals['type'] in ['out_invoice', 'out_refund']:
                vals['registration_key'] = fp.sii_registration_key_sale.id
            if vals['type'] in ['in_invoice', 'in_refund']:
                vals['registration_key'] = fp.sii_registration_key_purchase.id
        if vals.get('sii_enabled', False):
            vals.pop('sii_enabled')
        invoice = super(AccountInvoice, self).create(vals)
        return invoice
```

**Comment by acysos** [comment]
Hola,

@ljsalvatierra-binovo es extraño que te llegue el valor sii_enabled al campo vals, es un campo de tipo related. Si llega en el vals intenta escribirlo en la compañía pero un usuario no administrador no se le debe dar permisos para editar los dato de la compañía.

De todas formas he añadido el cambio, es una medida de seguridad que no impide el funcionamiento en https://github.com/acysos/odoo-addons/commit/96de99844ee497c5713f56f853083ee3c9385002

Gracias por el aviso

**Comment by ljsalvatierra-binovo** [comment]
Hola,

Exactamente, me ha parecido muy extraño que en un campo de ese tipo intente realizar una escritura "inversa" en la compañía, cuando además ya está establecido ese campo ("sii_enabled").

Gracias por vuestra rápida respuesta :). Un saludo.
